name: conda-environment-sphinx
dependencies:
  - python==3.14.0
  - pip
  - pip:
      - sphinx==9.1.0
      - sphinx-click==6.2.0
      - numpydoc==1.10.0
      - sphinx-copybutton==0.5.2
      - furo==2025.12.19
      - myst_parser==5.0.0
      - notebook==7.5.2
      - ipywidgets==8.1.8
      - matplotlib==3.10.8
      - myst-nb==1.3.0
      - toml==0.10.2
