dependencies:
  - python==3.12
  - pytest==8.1.1
  - pip
  - pystac==1.8.3
  - tox==4.11.4
  - netcdf4==1.6.5
  - syrupy==4.6.1
  - compliance-checker==5.1.1
  - pip:
    - pytest-order==1.2.1
    - freezegun==1.5.1
    - pytest-cov==5.0.0
    - pytest-xdist==2.1.1
